api/index.js, api/src/models/Plan.js
First version of the PLAN model to add to the Data Base models
=> feat(api/src/models):add model PLAN to DB

api/src/models/Category.js, api/src/models/SubCategory.js
Category and subcategory model creation.
=> Feat(api/models): category and subcategory models

client/package.json, client/src/App.js, client/src/Redux/Actions/Actions.js, client/src/Redux/Slices/postsSlice.js, client/src/Redux/Slices/usersSlice.js, client/src/Redux/store.js, client/src/index.js
=> Feat/creating redux-toolkit

api/index.js, api/src/db.js, api/src/models/Plan.js
Updated Number for Integer in DB model Plan. and added relationship between models in db.js file
=> Refactor(api/src/models):Refactoring of model

api/src/models/Feedback.js
=> Feat(api/models): feedback model creation

client/src/Components/CreatePost/CreatePost.jsx
=> feat(client/component/createpost):formpost

client/src/Components/Home/Footer/AboutUs.jsx, client/src/Components/Home/Footer/ContactUs.jsx, client/src/Components/Home/Footer/PrivacyPolicy.jsx, client/src/Components/Home/Footer/TermsOfUse.jsx
=> refactor/(src/Components/Home/Footer/): routes of the footer finished

client/src/App.js
Adding the routes of the footer in the app
=> refactor/(client/src/App.js): adding the routes of the footer

client/src/Components/Home/Navbar/Search.jsx, client/src/Redux/Actions/Actions.js, client/src/Redux/Slices/postsSlice.js, client/src/Redux/Slices/usersSlice.js
=> feat(client/redux):adding action post by search

api/src/app.js, api/src/routes/router.js
Fixing app.js and routes/router, module.exports was missing and app.js was not requiring the correct path for routing
=> Fix(api/routes/router & api/app)database fix

api/src/models/Category.js, api/src/routes/services.js
Category and subcategoy are UNIFIED in Category model. 
Category model, function getCategory and postCategory was MODIFIED
=> Fix (api/routes): category and subcategory are unifed in Category

client/src/Components/CreatePost/CreatePost.jsx, client/src/Components/Home/Navbar/Navbar.jsx, client/src/Components/Home/Navbar/Navbar.module.css, client/src/Components/Home/Navbar/Search.jsx
add css styles, create post button, login and register
=> Refactor(client/Components/Navbar):add css styles and create post button

api/src/models/Post.js, api/src/routes/services.js
Post creation fixed and description of Post model can now storage more data
=> Fix(api/services) post creation fix

client/src/Redux/Actions/Actions.js, client/src/Redux/Slices/postsSlice.js
Ready the action to filter by subcategory
=> Refactor(client/Redux):add redux flow-action filtered by subcategory

client/src/App.css, client/src/Components/Home/Card/Card.module.css, client/src/Components/Home/Card/CardDetail.jsx, client/src/Components/Home/Card/Cards.jsx, client/src/Components/Home/DrawerCategories/DrawerCategories.module.css
=> Refactor(client/card): Card Changes

api/src/routes/router.js, api/src/routes/services.js
New route added to be able to modify any category, adding or deletting subCategories , and setting display in true or false.
Modified two files api/src/routes.services.js and api/src/routes.router.js
=> feat(api/routes/services&routerjs):New route added to modify Category

api/src/routes/router.js, api/src/routes/services.js
Added router to Get/user detail by id
=> Feat (api/routes) new Router to GET/UserDetail

client/src/Components/Home/DrawerCategories/DrawerCategories.jsx, client/src/Components/Home/Home.jsx
setting the page in 1 when filter by subcategory
=> fix/(client/src): DrawerCategories and Home paginated

README.md, client/src/Components/Home/Footer/Glosary.jsx, client/src/Components/Home/Footer/TermsOfUse.jsx, client/src/Components/Memberships/Membership.jsx
Create the component Membership without logic. Waiting for payments pasarel
=> Membership

api/src/routes/router.js, api/src/routes/services.js
Create and modify user is now combined in the same route "POST: /user"
When using the route "/user" its a must to send the properties {name, phone, country, email, image} as body.
=> Fix(api/routes) create and modify user

api/src/routes/router.js, api/src/routes/services.js
=> Feat (api/routes): UserContact added

api/src/routes/router.js, api/src/routes/services.js
=> Route User-ban

api/src/routes/router.js, api/src/routes/services.js
Changed the params in UserDetail
=> Fix (api/routes): change email params to ID

api/src/models/Plan.js, api/src/routes/router.js, api/src/routes/services.js
Model's plan modified
PUT/plan Modify added
POST/plan modified
=> Feat (api/routes): PUT/plan modify and POST/plan modified

client/src/Components/AdminPanel/CardsPost.jsx, client/src/Components/AdminPanel/Reports.jsx, client/src/Redux/Actions/Actions.js
=> ban post ready

client/src/Components/Home/Footer/Feedback.jsx, client/src/Components/Home/Footer/css/Feed.module.css
=> FRONT Feedback text

api/index.js, api/src/routes/router.js, api/src/routes/services.js, client/src/Components/AdminPanel/AdminPanel.jsx, client/src/Components/AdminPanel/CardsPost.jsx, client/src/Components/AdminPanel/CardsReviews.jsx, client/src/Components/AdminPanel/Reports.jsx, client/src/Components/User/Profile.jsx, client/src/Redux/Actions/Actions.js
Route for updating and banning a review was simplified to reflect the idea that the only person capable of reporting a review is the owner of that review. Updated all files affected by this change
=> fix(routes)changed route for review report and ban

api/src/routes/jsons.js, api/src/routes/services.js, client/src/Components/Memberships/Memberships.jsx, client/src/Redux/Actions/Actions.js
Fix planId in Users and modify membership premiun about remaining contacts
=> Plan unlimit
